{
    "debug": false,
    "featureManagerIsAlwaysOnlineEnabled": true,
    "featureManagerIsBrowserCacheTTLEnabled": true,
    "featureManagerIsBrowserIntegrityCheckEnabled": true,
    "featureManagerIsCacheLevelEnabled": true,
    "featureManagerIsChallengePassageEnabled": true,
    "featureManagerIsDevelopmentModeEnabled": true,
    "featureManagerIsFullZoneProvisioningEnabled": false,
    "featureManagerIsIpv6Enabled": true,
    "featureManagerIsIpRewriteEnabled": true,
    "featureManagerIsMinifyEnabled": true,
    "featureManagerIsProtocolRewriteEnabled": true,
    "featureManagerIsPurgeCacheEnabled": true,
    "featureManagerIsRailgunEnabled": true,
    "featureManagerIsScanEnabled": false,
    "featureManagerIsSecurityLevelEnabled": true,
    "featureManagerIsSSLEnabled": true,
    "locale": "en",
    "integrationName": "wordpress",
    "useHostAPILogin": false,
    "version": "1.0.0"
}